@apiUrl = http://localhost:3000/api
//{{apiUrl}}


# Autenticação de usuário 
POST {{apiUrl}}/login
Content-Type: application/json
 
{
    "email": "fulano@upf.br",
    "senha": "123"
}
###


# Obter a lista de colaboradores
GET {{apiUrl}}/colaboradores
Content-Type: application/json
###

# Inserir novo colaborador
POST {{apiUrl}}/colaboradores
Content-Type: application/json

{
 "nome": "Otávio Colaborador", 
 "email": "otaviocolaborador@upf.br",
 "senha": "123"
}
###

# Alterar colaborador
PUT {{apiUrl}}/colaboradores
Content-Type: application/json

{
 "_id": "623e5e42ecfd248af0e960f4",
 "nome": "Carlos", 
 "email": "183100@upf.br",
 "senha": "123456"
}
###

# Excluir um colaborador
DELETE {{apiUrl}}/colaboradores/623a61ca1b44b7e43f56850e
Content-Type: application/json
###

# Obter pelo id de colaborador
GET {{apiUrl}}/colaboradores/623a61ca1b44b7e43f56850e
Content-Type: application/json
###

# Obter colaborador filtrando
GET {{apiUrl}}/colaboradores/filtro/teste
Content-Type: application/json
###